# syntax=docker/dockerfile:1

FROM ghcr.io/osgeo/gdal:ubuntu-full-3.13.1

SHELL ["sh", "-exc"]

ARG USERNAME=ubuntu
ARG USER_UID=1000
ARG USER_GID=$USER_UID

LABEL org.opencontainers.image.url=https://github.com/ECMWFCode4Earth/atlantis/issues \
    org.opencontainers.image.title="ECMWF Atlantis Ubuntu Image" \
    org.opencontainers.image.description="ECMWF Atlantis Code4Earth" \
    org.opencontainers.image.vendor="ECMWF" \
    org.opencontainers.image.authors="lagamura, kalfasyan"

COPY --from=ghcr.io/astral-sh/uv:0.10 /uv /uvx /bin/

RUN apt-get -qq update && \
    apt-get install -y curl make g++ locales && \
    locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN mkdir -p /home/$USERNAME/.venv && chown $USER_UID:$USER_GID /home/$USERNAME/.venv

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PROJECT_ENVIRONMENT=/home/$USERNAME/.venv

USER $USERNAME