name: Check Notebooks Output

on:
  pull_request:
    paths:
      - "**.ipynb"
  push:
    branches:
      - main
    paths:
      - "**.ipynb"
  workflow_dispatch:

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check notebooks are stripped
        uses: kynan/nbstripout@34071b78c181af3bf5af955c1426466e096fc3db #v0.9.1
        with:
          paths: "**/*.ipynb"
